accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from accounts.views import signup

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(pattern_name="home")),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpensiveCategoryListView,
    AccountListView,
    ExpenseCategoryCreate,
    AccountCreate,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpensiveCategoryListView.as_view(),
        name="list_categories",
    ),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path(
        "categories/create/",
        ExpenseCategoryCreate.as_view(),
        name="create_category",
    ),
    path("accounts/create/", AccountCreate.as_view(), name="create_account"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3, null=True)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.vendor

accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth import login


def signup(request):
    # POST is like add something
    # checking to see if we got a request
    if request.method == "POST":
        # generate a form for them to sign up
        form = UserCreationForm(request.POST)
        # if the form is valid with everythign below.
        if form.is_valid():
            # testing to see if user is adding a username and password
            username = request.POST.get("username")
            password = request.POST.get("password")
            # tying user to the username and password
            user = User.objects.create_user(
                username=username, password=password
            )
            # save the username
            user.save()
            # mush the request of logging in with the user.
            login(request, user)
            # direct back to home
            return redirect("home")
    # if the request was not recieved.
    else:
        # we bring up the form
        form = UserCreationForm()
    # add form to context
    context = {"form": form}
    # render it
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from receipts.models import Receipt, Account, ExpenseCategory
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ExpensiveCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "expense/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCategoryCreate(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "expense/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "account/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreate(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "account/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account_list")


class ReceiptCreateView(CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'create_receipt' %}">Create</a>
                </li>
                <li>
                    <a href="{% url 'home' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'list_categories' %}">Expense List</a>
                </li>
                <li>
                    <a href="{% url 'create_category' %}">Create Category</a>
                </li>
                <li>
                    <a href="{% url 'account_list' %}">Account List</a>
                </li>
                <li>
                    <a href="{% url 'create_account' %}">Create Account</a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'signup' %}">Signup</a>
                </li>
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock content %}
</body>
</html>

receipts/templates/expense/create.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>Create Category</h1>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div>
                <button>Create</button>
            </div>
        </form>
    </div>
</main>
{% endblock content %}

receipts/templates/expense/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <h1>My Expense</h1>
        <table>
            <thead>
                <th>Name</th>
                <th>Number of Receipts</th>
            </thead>
            <tbody>
                {% for exp in expensecategory_list %}
                <tr>
                    <td>{{exp.name}}</td>
                    <td>{{exp.receipts.all|length}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>Create Receipt</h1>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div>
                <button>Create</button>
            </div>
        </form>
    </div>
</main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </thead>
            <tbody>
                {% for r in receipt_list %}
                <tr>
                    <td>{{r.vendor}}</td>
                    <td>{{r.total}}</td>
                    <td>{{r.tax}}</td>
                    <td>{{r.date|date:"m-d-Y"}}</td>
                    <td>{{r.category}}</td>
                    <td>{{r.account}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
{% endblock content %}